### ISSUE TITLE
If attributes have alternate names, its value returns None in search.

### ISSUE THREAD

**Issue by MrAwesomeGeek** [cannatag/ldap3#378] opened 2017-07-03 21:45 UTC
Hi Giovanni,

If an attribute such as "givenname" has alternate names such as "givenname" and "gn", and we search based on one of em, it returns None even if it has a value. I have recently upgraded to 2.2.4 and I am facing this issue. When I was using 2.2.0, and I had the same multiple name problem, it used to throw me an error instead of returning None, and I used AttrDef to fix it.The same thing is not helping me now. Can you please help me with this?

**Comment by cannatag** [comment] 2017-07-04 22:49
Hi,
The following code works for me:
```
from ldap3 import Server, Connection, Reader, ObjectDef
c = Connection('MY_SERVER', 'MY_USER', 'MY_PASSWORD')
c.bind()
o = ObjectDef('inetorgperson', c)
r = Reader(c, o, 'o=test', '(cn=*)')
r.search()
e = r[0]
print(e.cn)
print(e.commonname)
```
In this case I get the same value for cn and commonname.

What is your use case?

**Comment by MrAwesomeGeek** [comment] 2017-07-05 16:06
I think there's some confusion. Imagine after instantiating an entry by defining its specific properties, the object contains the following.

OBJ:  'interorgperson'
MUST: 'givenname', 'commanname', 'name'
MAY: 'first_name', 'LastName'

I defined each element, and when I query based on name, I'm supposed be getting a value for each one of them. Instead, for attributes with alternate names such as 'givenname', which can also be called 'gn', its returning None in 2.2.4. I had the same problem in 2.2.0, where it threw error saying "ldap3.core.exceptions.LDAPCursorError: attribute ''gn" not in object class 'interorgperson' for entry.  I did something like this  object += AttrDef('givenname', key='given_name') to tackle that problem in 2.2.0. This time in 2.2.4, its not throwing an error, which is good, its just returning None.

**Comment by cannatag** [comment] 2017-07-05 16:26
Now I understand, could you give me some code to show the error?

**Comment by MrAwesomeGeek** [comment] 2017-07-05 17:03
class Entry(object):
 
    def __init__(self, connection):
        self.connection = connection
        self.object = ObjectDef(self.object_definition, connection)
 
        self._reader = None
 
    @property
    def reader(self):
        if self._reader:
            return self._reader
        else:
            self._reader = Reader(self.connection, self.object, self.ldif)
            return self._reader
 
 
 
class PersonEntry(Entry):
 
    object_definition = 'Person'
 
    def __init__(self, connection):
        super(PersonEntry, self).__init__(connection)
        schema = ****

        self.object += [AttrDef('uname', key='username'),
                        AttrDef('gn', key='given_name'),
                        AttrDef('cn', key='common_name')]

I was doing this until now in 2.2.0.. and when I query using username it gives me a list of values..
[{'username': 'xxxx', given_name: 'yyyy'.....}]

I removed the AttrDef stuff in 2.2.4, since it was giving me a key error. But now its giving me 
[{'username': None, give_name:None}.. 

***attributes which do not have an alternate name are returning correct values

**Comment by cannatag** [comment] 2017-07-06 06:10
I'm not able to replicate the error. Can you tell me what LDAP server are you connecting to?

Furthermore when you use ``self.object = ObjectDef(self.object_definition, connection)`` the ObjectDef definition is built automatically from the server schema, so you don't have to use AttrDef at all.

The following code (adapted from yours) works for me:

```
from ldap3 import Connection, ObjectDef, AttrDef, Reader
MY_SERVER = 'ipa.demo1.freeipa.org'
MY_USER = 'uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'
MY_PASSWORD = 'Secret123'
MY_BASE = 'cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'

class Entry(object):
    def __init__(self, connection):
        self.connection = connection
        self.object = ObjectDef(self.object_definition, connection)
        self._reader = None

    @property
    def reader(self):
        if self._reader:
            return self._reader
        else:
            self._reader = Reader(self.connection, self.object, MY_BASE)
            return self._reader

class PersonEntry(Entry):
    object_definition = 'Person'

    def __init__(self, connection):
        super(PersonEntry, self).__init__(connection)
        #schema = ****

c = Connection(MY_SERVER, MY_USER, MY_PASSWORD)
c.bind()
p = PersonEntry(c)
p.reader.search()
print(p.reader)
print(p.reader[0])
```

it prints out the Reader cursor and the first entry found:
```

CURSOR : Reader
CONN   : ldap://ipa.demo1.freeipa.org:389 - cleartext - user: uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org - not lazy - bound - open - <local: 192.168.1.100:61026 - remote: 52.57.162.88:389> - tls not started - listening - SyncStrategy - internal decoder
DEFS   : ['person'] [cn, description, objectClass, seeAlso, sn, telephoneNumber, userPassword]
ATTRS  : ['cn', 'description', 'objectClass', 'seeAlso', 'sn', 'telephoneNumber', 'userPassword']
BASE   : 'cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org' [SUB]
FILTER : '(objectClass=person)'
ENTRIES: 4 [executed at: 2017-07-06T08:06:13.181663]

DN: uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org - STATUS: Read - READ TIME: 2017-07-06T08:06:13.179673
    cn: Administrator
    objectClass: top
                 person
                 posixaccount
                 krbprincipalaux
                 krbticketpolicyaux
                 inetuser
                 ipaobject
                 ipasshuser
                 ipaSshGroupOfPubKeys
                 ipaNTUserAttrs
    sn: Administrator
```

It uses a public LDAP demo server. Please adapt this code to show the problem in 2.2.4. On this server there is no alias "gn" for givenname" you can use "cn" for "commonname".

**Comment by MrAwesomeGeek** [comment] 2017-07-06 22:49
I did some debugging. Apparently ldap is releasing the bunch of them as operational attributes, and if I have to search them , I have to search them with OA as prefix. The same happen't with given_name and surnname. They were being presented by ldap as 

OA_sn [OPERATIONAL]: xxxx, 
OA_gn [OPERATIONAL]: xxxx.  

When I am trying to search for these values individually. I was getting None, because I was searching for sn instead of OA_sn. Is that prefix behavior intended ?

**Comment by cannatag** [comment] 2017-07-06 23:11
That's not the intended behavior. sn and givenname definitely aren't operational attributes. I think that there's something wrong in the schema read from the server. Can you print out the server.schema object?

**Comment by cannatag** [comment] 2017-07-07 05:59
Please try latest code in dev. I've added an ``alias`` parameter in AttrDef that adds additional keys for the attribute. You can pass a single alias with ``alias=name`` or a sequence of aliases with ``alias=['name1', 'name2', 'name3']``

For example, with the following code:
```
from ldap3 import Connection, ObjectDef, AttrDef, Reader
MY_SERVER = 'ipa.demo1.freeipa.org'
MY_USER = 'uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'
MY_PASSWORD = 'Secret123'
MY_BASE = 'cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'

class Entry(object):
    def __init__(self, connection):
        self.connection = connection
        self.object = ObjectDef(self.object_definition)
        self._reader = None

    @property
    def reader(self):
        if self._reader:
            return self._reader
        else:
            self._reader = Reader(self.connection, self.object, MY_BASE)
            return self._reader

class PersonEntry(Entry):
    object_definition = 'Person'

    def __init__(self, connection):
        super(PersonEntry, self).__init__(connection)
        #schema = ****
        self.object += [AttrDef('surname', key='a1'),
                        AttrDef('cn', alias=['commonname', 'name'])]

c = Connection(MY_SERVER, MY_USER, MY_PASSWORD)
c.bind()
p = PersonEntry(c)
p.reader.search()
print(p.reader)
e = p.reader[0]
print(e)
print('a1', e.a1)
print('cn', e.cn)
print('commonname', e.commonname)
print('name', e.name)
```
I get:
```
CURSOR : Reader
CONN   : ldap://ipa.demo1.freeipa.org:389 - cleartext - user: cn=admin,o=resources - not lazy - bound - open - <local: 192.168.137.1:51006 - remote: 192.168.137.101:389> - tls not started - listening - SyncStrategy - internal decoder
DEFS   : ['Person'] [a1 <surname>, cn]
ATTRS  : ['cn', 'surname']
BASE   : 'o=resources' [SUB]
FILTER : '(objectClass=Person)'
ENTRIES: 1 [executed at: 2017-07-07T07:56:55.086235]

DN: cn=admin,o=resources - STATUS: Read - READ TIME: 2017-07-07T07:56:55.086235
    a1: admin
    cn: admin

a1 admin
cn admin
commonname admin
name admin
```

As you can see either ``cn``, ``commonname`` and ``name`` are "pointers" to the very same object.

**Comment by cannatag** [comment] 2017-07-07 06:18
Note that you don't have to pass the connection to the ObjectDef else AttrDefswould be automatically created for all attributes in the schema.

**Comment by MrAwesomeGeek** [comment] 2017-07-07 15:05
Okay. I've tried a bunch of things that you have suggested. Thank you for such prompt replies. By givenname, I was being generic. I was just telling you as an example parameter. After my part of the code 

from ldap3 import Connection, ObjectDef, AttrDef, Reader
MY_SERVER = 'ipa.demo1.freeipa.org'
MY_USER = 'uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'
MY_PASSWORD = 'Secret123'
MY_BASE = 'cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'

class Entry(object):
    def __init__(self, connection):
        self.connection = connection
        self.object = ObjectDef(self.object_definition, connection)
        self._reader = None

    @property
    def reader(self):
        if self._reader:
            return self._reader
        else:
            self._reader = Reader(self.connection, self.object, MY_BASE)
            return self._reader

class PersonEntry(Entry):
    object_definition = 'Person'
    schema = XXXXXXXX

    def __init__(self, connection):
        super(PersonEntry, self).__init__(connection)


the entries I am getting are something like this...

DN: user_name=admin,cn=xxxx,cn=xxxx,dc=xxxx,dc=freeipa,dc=xxxx - STATUS: Read - READ TIME: 2017-07-07T09:55:49.654850

OA_sn [OPERATIONAL]: xxxxxxx
OA_c [OPERATIONAL]: US
Similar 4 or 5 operational attributes

givenName: xxxx
objectClass: top
                     person
                     xxxxxxxxxxxxx

accountNumber: xxxxx
and other stuff...  

This is when I query it based on a single value of user_name. 

When I try the same thing without passing the connection to the ObjectDef, its throwing me some kind of error. Is this a intended behaviour.

**Comment by MrAwesomeGeek** [comment] 2017-07-07 17:20
Actually alias thing works perfectly. It solves everything. When are planning to release 2.2.5?

**Comment by cannatag** [comment] 2017-07-08 04:48
Hopefully it will be released before the end of July.

**Comment by MrAwesomeGeek** [comment] 2017-07-21 21:28
I have a new doubt. Imagine this being the same code.. i.e
rom ldap3 import Connection, ObjectDef, AttrDef, Reader
MY_SERVER = 'ipa.demo1.freeipa.org'
MY_USER = 'uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'
MY_PASSWORD = 'Secret123'
MY_BASE = 'cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org'

class Entry(object):
    def __init__(self, connection):
        self.connection = connection
        self.object = ObjectDef(self.object_definition)
        self._reader = None

    @property
    def reader(self):
        if self._reader:
            return self._reader
        else:
            self._reader = Reader(self.connection, self.object, MY_BASE)
            return self._reader

class PersonEntry(Entry):
    object_definition = 'Person'
    schema = ******

    def __init__(self, connection):
        super(PersonEntry, self).__init__(connection)
        #schema = ****
        self.object += [AttrDef('surname', key='a1'), 
                               AttrDef('givenname', key='a2'),
                               AttrDef('blahblah', key='blah')]

Imagine I map blahblah in the object, and its not there, it'll throw me an error in search saying..
ldap3/abstract/cursor.py", line 461, in search
ldap3/abstract/cursor.py", line 233, in _execute_query
ldap3/core/connection.py", line 750, in search

ldap3.core.exceptions.LDAPAttributeError: invalid attribute type BlahBlah

Is there a way to make these attributes optional. My problem is I am mapping an attribute, and its not there in the object. I saw changing get_info in server from all to DSA fixes it, but its causing all other problems. So is there an easy way to fix it.

**Comment by cannatag** [comment] 2017-08-02 14:58
Please check if this issue still exists with the 2.3 version of ldap3 (just released).

Thanks,
Giovanni

**Closed** 2017-08-26 15:43 UTC
