### ISSUE TITLE
Support Server Name Indication (SNI) for LDAPS

### ISSUE THREAD

**Issue by edmundcraske** [cannatag/ldap3#366] opened 2017-06-15 14:10 UTC
Hi, we have an environment where we need to be able to hit multiple LDAPS endpoints via a reverse proxy, and would like to be able to differentiate based upon the hostname supplied by the client, which could be done using TLS Server Name Indication (SNI). However this library does not appear to pass 'server_hostname' to the ssl library when initiating a connection, so SNI does not seem to be used. Is this something that is easily supported?

**Comment by cannatag** [comment] 2017-06-15 20:03
Hi, it would be great to have SNI, I will work on this in the weekend. To test it I must set up an environment lab with multiple LDAP server with different certificate. Is your reverse-proxy infrastructure available on the Internet for testing?

**Comment by cannatag** [comment] 2017-06-18 05:21
Please can you check the code in dev? The Tls() object now has a new ``sni`` parameter that holds the name of the server you're connecting to. If the underlying python ssl library support the SSLContext object it will be used. I cannot check this because I don't have a multi-ldap proxy in my lab.

**Comment by cannatag** [comment] 2017-06-24 22:48
Hi, were you able to test the code in dev? I'm going to release the 2.2.5 version of ldap3 and I'd like to include this fix.

Thanks,
Giovanni

**Comment by edmundcraske** [comment] 2017-07-04 15:43
Hi Giovanni,
Sorry for not replying, I haven't looked at my notifications in a while. I'm not in a good position to test at this time, it was more of a 'handy feature request' than a 'I need this fixing right now!' kind of issue :) I'll have a look over your code though!

**Comment by edmundcraske** [comment] 2017-07-04 15:48
I've taken a look at the code, and I believe that it would be better to just always hand the hostname that has been passed to the library through to ssl to use for SNI, rather than making it something that has to be configured separately - as I understand it the server would just ignore the SNI sent by the client if it is not configured to support/use it?

**Comment by cannatag** [comment] 2017-07-04 22:16
I prefer to be explicit here, because always passing the host name could have side effects I'm not aware and could change the behaviour of the ldap3 library from the previous versions. 

The problem is that I can't do any testing on this issue, so can't be sure if it's working or not.

**Comment by cannatag** [comment] 2017-08-02 15:01
Fixed in release 2.3 of ldap3.

**Closed by cannatag** 2017-08-02 15:01 UTC

**Comment by cfelder** [comment] 2021-01-03 00:34
Hello and a happy new year?

has this ever been verified?

I am just testing SNI on my side and I am not sure whether it is a problem with my setup or with sni support in this client.

**Comment by cfelder** [comment] 2021-01-03 14:05
Needs further investigation on my side. I just checked with openssl sclient and starttls ldap option and currently my two backends are shuffling on each connection instead of being selected in respect to sni

**Comment by cfelder** [comment] 2021-01-04 22:54
As I did not find an existing tcp reverse proxy server supporting sni for ldap, I've just started to write my own one in go. I've tested this using

```
$ openssl s_client -starttls ldap -connect ldap2.centos-8.shared:3389
```

and

```python
conn = Connection(Server("centos-8", 3389,
                         tls=Tls(validate=ssl.CERT_NONE, sni="ldap2.centos-8.shared")),
                  auto_bind=AUTO_BIND_TLS_BEFORE_BIND)
```

I can confirm the ldap3 sni implementation works fine though.
