### ISSUE TITLE
Active Directory users can access with the old and new password

### ISSUE THREAD

**Issue by fcaspani01** [cannatag/ldap3#807] opened 2020-03-26 08:40 UTC
Hi,
I've noticed that Active Directory (Microsoft) users can access with the old and new password after change it with ldap3.
Does exists a python ldap3 client's cache for ldap connections to ms AD?

**Comment by fcaspani01** [comment] 2020-03-26 10:50
Update: 
https://support.microsoft.com/en-us/help/906305/new-setting-modifies-ntlm-network-authentication-behavior

> The lifetime period of the old password can be configured by editing the registry on a domain controller. No restart is required for this registry change to take effect.

**Comment by zorn96** [comment] 2020-04-29 07:37
@fcaspani01 should this be closed as "Not a Bug" then? it seems like this is server-side behavior

**Comment by fcaspani01** [comment] 2020-04-29 07:50
Yes, I confirm this is a server side behaviour.

**Closed** 2020-04-29 07:51 UTC
