### ISSUE TITLE
pyasn1.error.PyAsn1Error: Attempted "__bool__" operation on ASN.1 schema object

### ISSUE THREAD

**Issue by ipsec** [cannatag/ldap3#483] opened 2018-01-25 19:50 UTC
I getting this error while using extend.novell.get_universal_password() on ldap3 2.4.1 with pyasn1 0.4.2
How to fix?

**Comment by etingof** [comment] 2018-01-25 19:53
I can guess that the root cause is that you are trying to access some optional and non-initialized ASN.1 field.

A reproducer might be helpful here. ;)

**Comment by cannatag** [comment] 2018-01-26 21:16
Please check code in dev, It should work now.

@etingof This is the same problem I had when checking for presence of a PyAsn1 value without using the ``hasValue()`` method.

**Comment by cannatag** [comment] 2018-04-14 15:40
Fixed in v2.5.

**Closed by cannatag** 2018-04-14 15:40 UTC
Labels: Fixed, Waiting answer from user, bug
