### ISSUE TITLE
Connection to LDAP server issue

### ISSUE THREAD

**Issue by tazou** [cannatag/ldap3#334] opened 2017-04-05 12:48 UTC
Hello,
Thanks for this module ! The abstraction and documentation is great.

I have a connexion problem when I try to bind my LDAP server.
You can see details here : 

**Connection test to the LDAP server : (OK)**
(py361) guillaume:~:$ telnet ldap-jaune.lan 389
Trying 10.200.207.223...
Connected to ldap3.lan.
Escape character is '^]'.
quit
0$x
P�1.3.6.1.4.1.1466.20036Connection closed by foreign host.

**Version of my Python venv :**
(py361) guillaume:~:$ python -V
Python 3.6.1

**Connexion test to the LDAP server with python :**
(py361) guillaume:~:$ python pocldap.py 
Traceback (most recent call last):
  File "pocldap.py", line 3, in <module>
    conn = Connection(server, auto_bind=True)
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/core/connection.py", line 327, in __init__
    self.bind(read_server_info=True)
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/core/connection.py", line 592, in bind
    self.refresh_server_info()
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/core/connection.py", line 1303, in refresh_server_info
    self.server.get_info_from_server(self)
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/core/server.py", line 436, in get_info_from_server
    self._get_schema_info(connection)
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/core/server.py", line 414, in _get_schema_info
    self._schema_info = SchemaInfo(schema_entry, connection.response[0]['attributes'], connection.response[0]['raw_attributes']) if result else None
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/protocol/rfc4512.py", line 287, in __init__
    self.attribute_types = AttributeTypeInfo.from_definition(attributes.pop('attributeTypes', []))
  File "/home/guillaume/py361/lib/python3.6/site-packages/ldap3/protocol/rfc4512.py", line 439, in from_definition
    splitted = re.split('( NAME | DESC | OBSOLETE| X-| E-' + pattern + ')', object_definition[1:-1])
  File "/home/guillaume/make_python/python-3.6.1/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object

**The python script :**
(py361) guillaume:~:$ cat pocldap.py 
from ldap3 import *
server = Server('ldap-jaune.lan', get_info=ALL)
conn = Connection(server, auto_bind=True)
server.info

**A similar search with ldapsearch command is working fine :** 
(py361) guillaume:~:$ ldapsearch -x -h ldap-jaune.lan -b 'ou=utilisateurs,o=vdm' '(uid=guillaume)'

```
# extended LDIF
#
# LDAPv3
# base <ou=utilisateurs,o=vdm> with scope subtree
# filter: (uid=guillaume)
# requesting: ALL
#

# guillaume, utilisateurs, vdm
dn: uid=guillaume,ou=utilisateurs,o=vdm
[..snip..]
givenName: Guillaume
[..etc..]
```

**I installed your module in my venv with :** 
pip install ldap3

Is my import incorrect or some other things in my code ? 
Do you have an idea please ? :)
Thanks for your time,
Regards.

**Comment by cannatag** [comment] 2017-04-05 13:29
Hi, what kind of ldap server are you connecting to? Does it work If you set get_info=NONE when defining the Server object?

 I see you're using python 3.6.1. I've not tested ldap3 with that version of python yet. Will do some check today.

Bye,
Giovanni

**Comment by tazou** [comment] 2017-04-05 13:38
Hi Giovanni,
Thanks a lot for your help.
It's working fine with "get_info=NONE".

The LDAP server is Oracle DSEE7 (Directory Server Enterprise Edition 7.0).

Best regards.

**Comment by cannatag** [comment] 2017-04-05 14:40
I've tested with Python 3.6.1 and it worked as in 3.6.0. The problem is probably in some data sent by the server while reading the schema. 

If you use get_info=NONE you lose the ability to automatically convert data to their python values, and this is very useful especially if you're using the abstraction layer.

I'd like to investigate more, but I've not access to an Oracle DSEE7 instance.

**Comment by tazou** [comment] 2017-04-06 07:35
Hi Giovanni,
I made a tcpdump during the script execution to try to debug the case. (with get_info=ALL)
I attach it here, can you see if you localize the problem ?
I see some strange packet at packet number from 406 to 409.
Thanks for your help :)
[python-ldap.cap.zip](https://github.com/cannatag/ldap3/files/901820/python-ldap.cap.zip)

**Comment by cannatag** [comment] 2017-04-06 14:36
Hi, at packet 406 the server decides to close the connection. It sends an "Unsolicited Notice of Disconnection" in an extended response (1.3.6.1.4.1.1466.20036 is the standard OID for the Notice of Disconnection, see paragraph 4.4.1 at  https://tools.ietf.org/html/rfc4511):
```
Lightweight Directory Access Protocol
    LDAPMessage extendedResp(0)
        messageID: 0
        protocolOp: extendedResp (24)
            extendedResp
                resultCode: other (80)
                matchedDN: 
                errorMessage: 
                responseName: 1.3.6.1.4.1.1466.20036 (iso.3.6.1.4.1.1466.20036)
```
You should check on your server why this is happening. The server sent the full schema in packet 405, then the client send a FIN + ACK TCP packet (at 405) and the server closes sending the Notice (406). This should not happen. It seams as if your client code is closing the connection in an abrupt way.

Can you send me the client code that generates this dump?

Thanks,
Giovanni

**Comment by tazou** [comment] 2017-04-06 15:01
Hi Giovanni,
Thank you :)
Yes the client code is : 
```
gduale:~:$ cat pocldap.py 
from ldap3 import *
def get_ldap_info(u):
    with Connection(Server('ldap-jaune.vdm.mars', port=389, use_ssl=False, get_info=ALL),
                    auto_bind=AUTO_BIND_NO_TLS,
                    read_only=True,
                    check_names=True,
                    user='', password='') as c:
 
        c.search(search_base='ou=utilisateurs,o=vdm',
                 search_filter='(&(uid=' + u + '))',
                 search_scope=SUBTREE,
                 attributes=ALL_ATTRIBUTES,
                 get_operational_attributes=True)
 
    print(c.response_to_json())
    print(c.result)
 
get_ldap_info('gduale')

```
Best regards.

**Comment by cannatag** [comment] 2017-04-07 19:15
I have no problem running your code. I've slightly modified to make it customizable and to make it recording a log in the ldap3.log file:

```
from ldap3 import *
import logging
logging.basicConfig(filename='ldap3.log', level=logging.DEBUG)
from ldap3.utils.log import set_library_log_detail_level, set_library_log_hide_sensitive_data, EXTENDED

set_library_log_detail_level(EXTENDED)
set_library_log_hide_sensitive_data(True)  # do not log password

server = 'my_server'
user = 'my_user'
password = 'my_password'
base = 'my_base'

def get_ldap_info(u):
    with Connection(Server(server, port=389, use_ssl=False, get_info=ALL),
                    auto_bind=AUTO_BIND_NO_TLS,
                    read_only=True,
                    check_names=True,
                    fast_decoder=False,  # to get a better log
                    user=user,
                    password=password) as c:
        c.search(search_base=base,
                 search_filter='(uid=' + u + ')',
                 search_scope=SUBTREE,
                 attributes=ALL_ATTRIBUTES,
                 get_operational_attributes=True)

    print(c.response_to_json())
    print(c.result)

get_ldap_info('user_to_query')
```

Can you adapt it to your environment and send me back the ldap3.log file?

Thanks,
Giovanni

**Comment by tazou** [comment] 2017-04-24 09:28
Hello Giovanni,
Sorry for the delay.

I run your script, here is the output : 

```
(py361) gduale:~:$ python pocldap.py 
Traceback (most recent call last):
  File "pocldap.py", line 31, in <module>
    get_ldap_info('user_to_query')
  File "pocldap.py", line 21, in get_ldap_info
    password=password) as c:
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/core/connection.py", line 325, in __init__
    self.bind(read_server_info=True)
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/core/connection.py", line 590, in bind
    self.refresh_server_info()
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/core/connection.py", line 1299, in refresh_server_info
    self.server.get_info_from_server(self)
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/core/server.py", line 436, in get_info_from_server
    self._get_schema_info(connection)
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/core/server.py", line 414, in _get_schema_info
    self._schema_info = SchemaInfo(schema_entry, connection.response[0]['attributes'], connection.response[0]['raw_attributes']) if result else None
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/protocol/rfc4512.py", line 287, in __init__
    self.attribute_types = AttributeTypeInfo.from_definition(attributes.pop('attributeTypes', []))
  File "/home/gduale/py361/lib/python3.6/site-packages/ldap3/protocol/rfc4512.py", line 439, in from_definition
    splitted = re.split('( NAME | DESC | OBSOLETE| X-| E-' + pattern + ')', object_definition[1:-1])
  File "/home/gduale/make_python/python-3.6.1/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
```

You can find in attachment the ldap3.log file.

For information, since the begining I try to bind anonymously.
[ldap3.log.zip](https://github.com/cannatag/ldap3/files/951224/ldap3.log.zip)




Thank you again.
Best regards.

**Comment by cannatag** [comment] 2017-04-25 16:41
Hi, can you send me also the tcpdump trace  when running the script? Now this seems different from the previous one. You here are able to receive the schema but there are some values that cannot be properly read. I need the tcpdump trace to see what the values are.

Thanks,
Giovanni

**Comment by tazou** [comment] 2017-04-26 09:32
Hi Giovanni,
Yes of course, you can find it in attachment.
Thank you,
Regards.
[ldap3-dump.cap.zip](https://github.com/cannatag/ldap3/files/957852/ldap3-dump.cap.zip)

**Comment by cannatag** [comment] 2017-04-26 15:35
HI, it seems that the server abruptely closed the connection. I don't understand why. ldap3 is simply requesting the schema, and this is a standard operation in LDAP.

Can you try the following? It's the same operation with the ldapsearch command. Please send me back the schema.log file.

ldapsearch -x -h my_server -s base -b "cn=schema" "objectclass=*" * + > schema.log

Thanks,
Giovanni

**Comment by tazou** [comment] 2017-04-27 06:54
Hi Giovanni,
I try your command but I remove the "* +" chars, because it fail with.

So, I execute this : 
ldapsearch -x -h ldap-jaune.vdm.mars -s base -b "cn=schema" "objectclass=*" > schema.log

You can find the log file here : [schema.log.zip](https://github.com/cannatag/ldap3/files/960731/schema.log.zip)

Thanks,
Regards.

**Comment by cannatag** [comment] 2017-04-27 07:03
What kind of failure do you have with the '+' sign? It means "read operational attributes" to get additional information from the server and should not affect the connection.

**Comment by tazou** [comment] 2017-04-27 07:19
Hi,
With your command with "* +", it list my current directory : 

```
gduale:~/tmp:$ ldapsearch -x -h ldap-jaune.vdm.mars -s base -b "cn=schema" "objectclass=*" * +
# extended LDIF
#
# LDAPv3
# base <cn=schema> with scope baseObject
# filter: objectclass=*
# requesting: myfile + 
#

# schema
dn: cn=schema

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

For information, my current directory : 
```
gduale:~/tmp:$ ls
myfile
```

Then, with just "+" : 
```
gduale:~/tmp:$ ldapsearch -x -h ldap-jaune.vdm.mars -s base -b "cn=schema" "objectclass=*" +
# extended LDIF
#
# LDAPv3
# base <cn=schema> with scope baseObject
# filter: objectclass=*
# requesting: + 
#

# schema
dn: cn=schema

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

```
Not a lot a result...

But without "* +", I have the previous log file.

Maybe I miss parenthesis somewhere ?

Thanks.

**Comment by cannatag** [comment] 2017-04-27 08:32
That means that your server doens't use the + for operational attributes. It's not a bad thing it's just not follwing rfc 3673. 

What I noticed is that in the ldapsearch the server is not sending the "ldapSyntaxes" that are a part of the schema. This are returned only when explicitly requested (or with the + sign). Can you try the following:

```
ldapsearch -x -h ldap-jaune.vdm.mars -b cn=schema -s base '(objectClass=subschema)' attributeTypes dITStructureRules objectClasses nameForms dITContentRules matchingRules ldapSyntaxes matchingRuleUse > schema1.log
```
This, as specified at http://www.openldap.org/faq/data/cache/1366.html request all the schema from the server, and is what is done by the ldap3 library, except for the '+' and '*' sign:
```
ldapsearch -x -h ldap-jaune.vdm.mars -b cn=schema -s base '(objectClass=subschema)' attributeTypes dITStructureRules objectClasses nameForms dITContentRules matchingRules ldapSyntaxes matchingRuleUse '*' '+'> schema2.log
```

Please send me back the schema1.log and schema2.log  files. 

Thanks,
Giovanni

**Comment by tazou** [comment] 2017-04-27 08:43
Hi,
Thanks a lot again for your help and explanations !
Here is the 2 logs you ask.
[schema2.log.zip](https://github.com/cannatag/ldap3/files/960970/schema2.log.zip)
[schema1.log.zip](https://github.com/cannatag/ldap3/files/960969/schema1.log.zip)

**Comment by cannatag** [comment] 2017-04-27 09:57
I've found a problem: in the schema there are some user defined attributes with description non in utf-8. for example:
```
"( vdmNomPatronymique-oid NAME 'vdmNomPatronymique' DESC 'Nom de jeune fille pour les femmes mari\xe9es' SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'user defined' )
```

that is latin-1 encoded.

The ldapsearch is probably dropping this out silently, in fact I didn't find it in the schemaX.log files you sent, while the ldap3 library tries to decode it.

I had a feature in the ldap3 library to check for not utf-8 dn names returned from the server, but this is not extended to the schema. Let me see if I can adapt it.

**Comment by cannatag** [comment] 2017-04-27 13:11
Can you test the code in dev? It should hopefuly work now.

**Comment by tazou** [comment] 2017-04-27 14:38
Hi,
How can I install the dev version please ?

I create a new python venv 3.6.1 and activate it, then : 
Clone the dev branch : 
git clone -b dev https://git@github.com/cannatag/ldap3.git
Install the deps : 
cd ldap3 ; pip install -r requirements.txt

And now how can I install inside the venv your ldap3-dev please ?

Thanks,
Regards.

**Comment by tazou** [comment] 2017-04-27 14:48
Hi,
I made the test, I have this error : 
```
(py361-testldap3-dev) gduale:~:$ python pocldap.py 
Traceback (most recent call last):
  File "pocldap.py", line 31, in <module>
    get_ldap_info('user_to_query')
  File "pocldap.py", line 21, in get_ldap_info
    password=password) as c:
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/core/connection.py", line 327, in __init__
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/core/connection.py", line 592, in bind
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/core/connection.py", line 1306, in refresh_server_info
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/core/server.py", line 434, in get_info_from_server
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/core/server.py", line 354, in _get_dsa_info
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/core/connection.py", line 762, in search
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/strategy/sync.py", line 142, in post_send_search
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/strategy/base.py", line 325, in get_response
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/strategy/sync.py", line 171, in _get_response
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/strategy/base.py", line 465, in decode_response
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/operation/search.py", line 503, in search_result_entry_response_to_dict
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/utils/conv.py", line 58, in to_unicode
TypeError: function takes exactly 5 arguments (1 given)
```
The python code executed is : 
```
(py361-testldap3-dev) gduale:~:$ cat pocldap.py 
from ldap3 import *
import logging
logging.basicConfig(filename='ldap3.log', level=logging.DEBUG)
from ldap3.utils.log import set_library_log_detail_level, set_library_log_hide_sensitive_data, EXTENDED

set_library_log_detail_level(EXTENDED)
set_library_log_hide_sensitive_data(True)  # do not log password

server = 'ldap-jaune.vdm.mars'
user = ''
password = ''
base = 'ou=utilisateurs,o=vdm'

def get_ldap_info(u):
    with Connection(Server(server, port=389, use_ssl=False, get_info=ALL),
                    auto_bind=AUTO_BIND_NO_TLS,
                    read_only=True,
                    check_names=True,
                    fast_decoder=False,  # to get a better log
                    user=user,
                    password=password) as c:
        c.search(search_base=base,
                 search_filter='(uid=' + u + ')',
                 search_scope=SUBTREE,
                 attributes=ALL_ATTRIBUTES,
                 get_operational_attributes=True)

    print(c.response_to_json())
    print(c.result)

get_ldap_info('user_to_query')
```

Must I update the file pocldap.py with some other args ?

Thanks,
Regards.

**Comment by cannatag** [comment] 2017-04-27 14:57
it should work as is. please send me your pocldap.py file and let me check.

**Comment by tazou** [comment] 2017-04-27 15:07
Hi,
Here is my pocldap.py file.
Thank you.
[pocldap.py.zip](https://github.com/cannatag/ldap3/files/962028/pocldap.py.zip)

**Comment by cannatag** [comment] 2017-04-27 19:28
Please update the ldap3 project from dev and try again. It should work now.

**Comment by tazou** [comment] 2017-04-28 07:26
Hi Giovanni,
I try again with the up-to-date dev branch, and it works fine !
Thanks a lot for all your help :) 
I just sent to you an Amazon Gift Card to thank you.
Best regards.

**Comment by cannatag** [comment] 2017-04-28 10:55
Good! Can you check if you have in the server.schema.attribute_types dictionary the attribute with the French description that I mentioned in my previous message? Now it should be properly decoded.

Thanks for the Amazon gift card, I really appreciate it!

Giovanni

**Comment by tazou** [comment] 2017-04-28 13:13
Hi,
Which python code must I execute to test what you ask please ?
Regards.

**Comment by cannatag** [comment] 2017-04-28 13:30
just try: 

```
print(c.server.schema.attribute_types['vdmNomPatronymique-oid'])
```
after the ``c.search(...)`` inside the ``with`` block.

It should print the description of your user defined attribute.

**Comment by tazou** [comment] 2017-04-28 13:41
Hi,
I try it, and I have this error : 
```
(py361-testldap3-dev) gduale:~/tmp/ldap3:$ python /home/gduale/pocldap.py 
Traceback (most recent call last):
  File "/home/gduale/pocldap.py", line 32, in <module>
    get_ldap_info('gduale')
  File "/home/gduale/pocldap.py", line 27, in get_ldap_info
    print(c.server.schema.attribute_types['vdmNomPatronymique-oid'])
  File "/home/gduale/py361-testldap3-dev/lib/python3.6/site-packages/ldap3-2.2.3-py3.6.egg/ldap3/utils/ciDict.py", line 64, in __getitem__
KeyError: 'vdmnompatronymique-oid'
```

So I changed : 
  print(c.server.schema.attribute_types['vdmNomPatronymique-oid'])
with : 
  print(c.server.schema.attribute_types['vdmNomPatronymique'])

And it is working, I have : 
```
(py361-testldap3-dev) gduale:~/tmp/ldap3:$ python /home/gduale/pocldap.py 
Attribute type: vdmNomPatronymique-oid
  Short name: vdmNomPatronymique
  Description: Nom de jeune fille pour les femmes mariées
  Single value: False
  Syntax: 1.3.6.1.4.1.1466.115.121.1.15 [('1.3.6.1.4.1.1466.115.121.1.15', 'LDAP_SYNTAX', 'Directory String', 'RFC4517')]
  Optional in: vdmpersonne
  Extensions:
    X-ORIGIN: user defined
```
Is it the informations you asked ?
Regards.

**Comment by cannatag** [comment] 2017-04-28 13:55
yes. The French text is encoded in latin-1 on your server, but now the ldap3 library can read it (the mariées word was cauising troubles).

Again, thanks a lot.
Bye,
Giovanni

**Comment by cannatag** [comment] 2017-04-30 07:54
Released in ldap3 v. 2.2.3.

**Closed by cannatag** 2017-04-30 07:54 UTC
