### ISSUE TITLE
RESTARTABLE + AUTO_BIND_TLS_BEFORE_BIND fails with LDAPMaximumRetriesError and underlying LDAPStartTLSError

### ISSUE THREAD

**Issue by duck-rh** [cannatag/ldap3#949] opened 2021-06-03 10:25 UTC
Quack,

(The is not the same issue as #925)

I am running am application using version 2.8.1 (2.9 is not in my distro but according to the changelog that would not change anything) and SYNC and that's working fine. To be able to handle network problem or server restart while in use I decided to follow the doc and advice given on this on this repo and switch to RESTARTABLE.

Here are the changes I made:
```
@@ -37,6 +37,10 @@ from typing import (
 )
 import copy
 from ldap3.protocol.oid import Oids
+import logging
+logging.basicConfig(filename='client_application.log', level=logging.DEBUG)
+from ldap3.utils.log import set_library_log_detail_level, OFF, BASIC, NETWORK, EXTENDED
+set_library_log_detail_level(EXTENDED)
 
 
 # command categories
@@ -470,7 +474,7 @@ def connect_ldap(config) -> Optional[ldap3.Connection]:
         # TODO: restart gracefully when LDAP server goes always
         #       handle reconnect when hitting LDAPSessionTerminatedByServerError and LDAPSocketOpenError exceptions
         #       RESTARTABLE does not work so far: restart tls in restartable not successful
-        ldap_con = ldap3.Connection(ldap_server, user=config['bind_dn'], password=config['bind_pw'], client_strategy=ldap3.SYNC, lazy=False, check_names=True)
+        ldap_con = ldap3.Connection(ldap_server, user=config['bind_dn'], password=config['bind_pw'], client_strategy=ldap3.RESTARTABLE, lazy=False, check_names=True, auto_bind=ldap3.AUTO_BIND_TLS_BEFORE_BIND, fast_decoder=False)
         if use_start_tls:
             ldap_con.start_tls()
         ldap_con.bind()
```

`use_start_tls` is always true in my case. I added logging and switch off `fast_decoder` as suggested in the doc to get more info.

In my application I read the root DSE once, it works, then shut down the LDAP server, restart the same read, and quickly restart  the server. The server is not loaded and is quickly up and running, and after waiting quite some time the program gives up with this trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cmd2/cmd2.py", line 2129, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/usr/lib/python3/dist-packages/cmd2/cmd2.py", line 2559, in onecmd
    stop = func(statement)
  File "/usr/lib/python3/dist-packages/cmd2/decorators.py", line 336, in cmd_wrapper
    return func(*args_list, **kwargs)
  File "/srv/data/Devel/ldapwalker/./ldapwalker", line 410, in do_cat
    entry = new_loc.fetch(operational_attrs=args.operational)
  File "/srv/data/Devel/ldapwalker/./ldapwalker", line 184, in fetch
    self._load_entry(full=True, operational_attrs=operational_attrs)
  File "/srv/data/Devel/ldapwalker/./ldapwalker", line 153, in _load_entry
    if self.ldap_con.search(dn, "(objectClass=*)", search_scope=ldap3.BASE, attributes=attrs):
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 846, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/restartable.py", line 245, in post_send_search
    raise e
  File "/usr/lib/python3/dist-packages/ldap3/strategy/restartable.py", line 234, in post_send_search
    ret_value = SyncStrategy.post_send_search(self, self.connection.send(self._current_message_type, self._current_request, self._current_controls))
  File "/usr/lib/python3/dist-packages/ldap3/strategy/restartable.py", line 195, in send
    raise LDAPMaximumRetriesError(self.connection.last_error, self.exception_history, self.restartable_tries)
ldap3.core.exceptions.LDAPMaximumRetriesError: LDAPMaximumRetriesError: restartable connection failed to send/Exception history:/    0 <class 'ldap3.core.exceptions.LDAPStartTLSError'>: restart tls in restartable not successful/Maximum number of retries reached: 30
EXCEPTION of type 'LDAPMaximumRetriesError' occurred with message: 'LDAPMaximumRetriesError: restartable connection failed to send/Exception history:/    0 <class 'ldap3.core.exceptions.LDAPStartTLSError'>: restart tls in restartable not successful/Maximum number of retries reached: 30'
```
I attached anonymized logs.
[client_application.log](https://github.com/cannatag/ldap3/files/6590907/client_application.log)

Regards.
\\_o<

**Comment by duck-rh** [comment] 2021-06-03 10:36
I did not realize at first but even when it works there is a failure to STARTTLS and an ERROR in the log, but fortunately when the next bind happen TLS is enabled. My server would have refused but sending the bind is clear would have been very very annoying. It looks like there's some kind of race condition.

**Comment by tlewis-ps** [comment] 2021-07-14 20:30
Fairly certain that the StartTLS error is caused by [this commit](https://github.com/cannatag/ldap3/commit/191667cff76e874164dce94dafebf0acf344bd41#diff-ce7de86797dfa53453a67a006f75cf8d719afbca29e1bcb488b728a102121404), and is an issue with RESTARTABLE and StartTLS that has been around since 2.8.

The AttributeError in the above commit was fixed in 2.8.1, but the current code in `restartable.py` seems to still have a bug:
```python
if self._restart_tls:  # restart tls if start_tls was previously used
    if self.connection.start_tls(read_server_info=False):
        error = 'restart tls in restartable not successful' + (' - ' + self.connection.last_error if self.connection.last_error else '')
        if log_enabled(ERROR):
            log(ERROR, '%s for <%s>', error, self)
        self.connection.unbind()
        raise LDAPStartTLSError(error)
```
I think this is missing a `not` and should be ` if not self.connection.start_tls(read_server_info=False): # create error`

**Comment by zorn96** [comment] 2021-07-15 00:10
PR out to fix this in https://github.com/cannatag/ldap3/pull/968

**Comment by zorn96** [comment] 2021-07-15 16:26
fix is merged into dev and will come out in the next release, 2.9.1

**Closed by zorn96** 2021-07-15 16:26 UTC

**Comment by duck-rh** [comment] 2021-09-15 09:20
Thanks @zorn96 (totally forgot to reply, sorry)
