### ISSUE TITLE
StandardInput instance has no attribute 'encoding'

### ISSUE THREAD

**Issue by cronicryo** [cannatag/ldap3#386] opened 2017-07-12 16:17 UTC
using this package in a 3d application where the python version 2.7.6

i get the error:  StandardInput instance has no attribute 'encoding'
**ldap3/utils/config.py:94**

ive modified the if statement as follows

#### FROM:

```python
if stdin and stdin.encoding:
    _DEFAULT_ENCODING = stdin.encoding
elif getdefaultencoding():
    _DEFAULT_ENCODING = getdefaultencoding()
else:
    _DEFAULT_ENCODING = 'utf-8'
```

#### TO:

```python
if stdin and (stdin.encoding if hasattr(stdin, "encoding") else False):
    _DEFAULT_ENCODING = stdin.encoding
elif getdefaultencoding():
    _DEFAULT_ENCODING = getdefaultencoding()
else:
    _DEFAULT_ENCODING = 'utf-8'
```

**Comment by cannatag** [comment] 2017-07-14 00:17
I've slightly modified your code: 

```
if stdin and hasattr(stdin, 'encoding') and stdin.encoding:
...
```

Can you try the code in dev and see if the problem is fixed?

Thanks.

**Comment by cannatag** [comment] 2017-08-02 14:55
Fixed in release 2.3 of ldap3.

**Closed by cannatag** 2017-08-02 14:55 UTC

**Comment by cronicryo** [comment] 2017-08-02 15:01
crap. i wish i saw your comment sooner. Just by looking at it it wouldnt fix the problem. hasattr is making sure that std.encoding doesnt run because the attribute doesnt exist which is throwing the error. 
in your modified version std.encoding is still running event though std doesnt have the encoding attribute
